name: app_services
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  hms_services:
    git:
      url: https://github.com/Mr-KrY4k/hms_services.git
      ref: dev

  gms_services:
    git:
      url: https://github.com/Mr-KrY4k/gms_services.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0